### ISSUE TITLE
Python terminates on Importing CGNN

### ISSUE THREAD

**Issue by kUser18** [GoudetOlivier/CGNN#1]
Dear Olivier,

I am studying your paper on causal generative neural networks, and am attempting implementation of a part of it.

This is regarding the CGNN code in your GitHub repository. I am facing an issue with the code.

I would be very grateful if you could reply and give me a bit of help.

I downloaded your CGNN repository. I followed the instructions, upgraded all packages in requirements.txt.

When I run
`
python setup.py install develop --user
`

It gives the following output
`running install`
`running bdist_egg`
`running egg_info`
`writing cgnn.egg-info/PKG-INFO`
`error: [Errno 13] Permission denied: 'cgnn.egg-info/PKG-INFO'`

So I installed ran the above command using sudo. The installation then goes through.

But, when I run
`sudo python`
`>>import cgnn`

The program terminates without any error.

Does this mean that the install develop step was not properly done?

Could you please help me with this issue?

If it helps,
I am using a virtual environment for python through Anaconda. Python 2.7 and Ubuntu 14.04.5 GNU/Linux 3.13.0

Please let me know if you want any more information from me.

Regards

**Comment by diviyank** [comment]
Hi,
Sorry for the delay, 
I think that using 
```sh
sudo python setup.py install develop --user
```
is actually not using your conda environment, which might bring problems into it.

Side note:
>for more investigation about why the program terminates, you could try the following : 
>1. Create a test file test.py 
>```python
>import cgnn
>print(cgnn.__version__)
>```
>2. Run it using gdb: 
>```sh
>gdb
>sudo python test.py
>```
 

The problem about permissions is actually strange : do you have all permissions on the git folder that you cloned?  What is the output of : 
```sh
which python 
```
when you try to install the package? (to check path problems).

One alternative would be to use the pytorch version of the algorithm available on our other package: 
[https://github.com/Diviyan-Kalainathan/CausalDiscoveryToolbox/](https://github.com/Diviyan-Kalainathan/CausalDiscoveryToolbox/)

Best,
Diviyan

**Comment by kUser18** [comment]
I did an install on a fresh system and it worked. Thank you.
